import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../components/contexts/AuthContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Student Data Analysis",
  description: "Generated by K.R.Hemanth",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="sticky top-0 z-40">
          <div className="h-px w-full bg-gradient-to-r from-transparent via-red-200 to-transparent" />
        </div>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
